aws:
  file_upload_s3_bucket_name: govuk-forms-dev-file-upload
  ses_submission_email_configuration_set_name: bounces_and_complaints_handling_rule

ses_submission_email:
  from_email_address: "local-test@dev.forms.service.gov.uk"
  reply_to_email_address: "local-test@dev.forms.service.gov.uk"

submission_status_api:
  secret: test_token

retain_submissions_for_seconds: 60
