forms_admin:
  # URL to form-admin
  base_url: http://localhost

ses_submission_email:
  from_email_address: govuk_forms@example.com
  reply_to_email_address: no-reply@example.com

file_upload:
  poll_scan_status_wait_milliseconds: 50
  poll_scan_status_max_attempts: 2
