active_record_encryption:
  primary_key: CC2SOludR0L15FLQkLNv8sbiQ5yNyHiF
  deterministic_key: vN8HaxVlbWVnohKU0aV8p36nwYEK1hZN
  key_derivation_salt: k7cODzIzpjWkKKGqVnabRzXtTgLnT813

forms_admin:
  # URL to form-admin
  base_url: http://localhost

ses_submission_email:
  from_email_address: govuk_forms@example.com
  reply_to_email_address: no-reply@example.com

submission_status_api:
  secret: test_token

file_upload:
  poll_scan_status_wait_milliseconds: 50
  poll_scan_status_max_attempts: 2
