forms_admin:
  # URL to form-admin
  base_url: http://localhost

forms_api:
  # URL to form-api endpoints
  base_url: http://localhost:9292
  enabled_auth: false
  # Authentication key to authenticate forms-runner to forms-api
  auth_key: 12345
